MvcStok/Controllers/AdminController.cs
using MvcStok.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcStok.Controllers
{
    public class AdminController : Controller
    {
        DbMvcStokEntities db=new DbMvcStokEntities();
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult CreateAdmin()
        {
            return View();

        }
        [HttpPost]
        public ActionResult CreateAdmin(TBLAdmin a)
        {
            db.TBLAdmin.Add(a);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class KategoriController : Controller
    {
        DbMvcStokEntities db = new DbMvcStokEntities();
        public ActionResult Index()
        {
            var kategoriler = db.TBLKategori.ToList(); // var değişkeninin sebebi kategorilerin içerisine yazı,sayı,karakter gibi bir çok şey gelebileceğinden tanımlanmıştır.
            return View(kategoriler);
            
        }
        [HttpGet]
        public ActionResult CreateKategori()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateKategori(TBLKategori p)
        {
            db.TBLKategori.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DeleteKategori(int id)
        {
           var ktg= db.TBLKategori.Find(id);
            db.TBLKategori.Remove(ktg);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult GetKategori(int id)
        {
            var ktgr = db.TBLKategori.Find(id);      
            return View("GetKategori",ktgr);
        }
        public ActionResult UpdateKategori(TBLKategori k)
        {
            var ktg = db.TBLKategori.Find(k.Id);
            ktg.Ad = k.Ad;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

MvcStok/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace MvcStok.Controllers
{
    public class MusteriController : Controller
    {
        DbMvcStokEntities db= new DbMvcStokEntities();
        [Authorize]
        public ActionResult Index(int sayfa=1)
        {
            //var musteriliste=db.TBLMusteri.ToList();
            var musteriliste = db.TBLMusteri.Where(x=>x.Durum==true).ToList().ToPagedList(sayfa, 3);
            return View(musteriliste);
        }
        [HttpGet]
        public ActionResult CreateMusteri()
        {
            return View();

        }
        [HttpPost]
        public ActionResult CreateMusteri(TBLMusteri p)
        {
            if(!ModelState.IsValid)
            {
                return View("CreateMusteri");
            }
            p.Durum = true; // Verinin eklendiğinde durumunu null'dan kurtarıp true yapar ve tabloda gösterilmesini sağlar.
            db.TBLMusteri.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult DeleteMusteri(TBLMusteri p)
        {
            var musteribul = db.TBLMusteri.Find(p.Id);
            musteribul.Durum = false; //var olan ürünün durumunu false olarak düzenlicek ve passive çekecek.
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult GetMusteri(int id)
        {
            var mus = db.TBLMusteri.Find(id);           
            return View("GetMusteri", mus);
        }
        public ActionResult UpdateMusteri(TBLMusteri t)
        {
            var mus = db.TBLMusteri.Find(t.Id);
            mus.Ad=t.Ad;
            mus.Soyad=t.Soyad;
            mus.Sehir=t.Sehir;
            mus.Bakıye = t.Bakıye;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/Controllers/UrünController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class UrünController : Controller
    {
        DbMvcStokEntities db = new DbMvcStokEntities();
        public ActionResult Index(string p)
        {
            //var urunler = db.TBLUrunler.Where(x=>x.Durum==true) ToList();
            var urunler = db.TBLUrunler.Where(x => x.Durum == true);
            if (!string.IsNullOrEmpty(p))
            {
                urunler = urunler.Where(x => x.Ad.Contains(p)&&x.Durum==true);//Ürünler içerisinde ad'a göre arama yapan bir işlem ama durumu true olanlar içerisinden...
            }
            return View(urunler.ToList()); ;
        }
        [HttpGet]
        public ActionResult CreateUrün()
        {// Amaç Ürünün kategorisini listeden çekebilmek (DropdownList)
            List<SelectListItem> ktg = (from x in db.TBLKategori.ToList()
                                        select new SelectListItem
                                        {
                                            //Display(Kullanıcının gördüğü)
                                            Text = x.Ad,

                                            //Value(Arka tarafta çalışan)
                                            Value = x.Id.ToString()

                                        }).ToList();

            //Controller daki değerleri başka sayfalara taşımak için "ViewBag" kullanılır.
            ViewBag.drop = ktg;
            return View();
        }
        [HttpPost]
        public ActionResult CreateUrün(TBLUrunler t)
        {
            var ktgr = db.TBLKategori.Where(x => x.Id == t.TBLKategori.Id).FirstOrDefault();
            t.TBLKategori = ktgr;
            db.TBLUrunler.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult GetUrün(int id)
        {
            List<SelectListItem> kat = (from x in db.TBLKategori.ToList()
                                        select new SelectListItem
                                        {
                                            Text = x.Ad,
                                            Value = x.Id.ToString()
                                        }).ToList();

            var ktgr = db.TBLUrunler.Find(id);
            ViewBag.urunkategorı = kat;
            return View("GetUrün", ktgr);
        }
        public ActionResult UpdateUrün(TBLUrunler p)
        {
            var urun = db.TBLUrunler.Find(p.Id);
            urun.Ad = p.Ad;
            urun.Marka = p.Marka;
            urun.Stok = p.Stok;
            urun.SatisFiyat = p.SatisFiyat;
            urun.AlısFiyat = p.AlısFiyat;
            var ktg = db.TBLKategori.Where(x => x.Id == p.TBLKategori.Id).FirstOrDefault();
            urun.Kategori = ktg.Id;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DeleteUrün(TBLUrunler p1)
        {
            var urunbul = db.TBLUrunler.Find(p1.Id);
            urunbul.Durum = false; //var olan ürünün durumunu false olarak düzenlicek ve passive çekecek.
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/Views/Shared/Admin_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC Stok", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Ürünler", "Index", "Urün")</li>
                    <li>@Html.ActionLink("Müşteriler", "Index", "Musteri")</li>                  
                    <li>@Html.ActionLink("Kategoriler", "Index", "Kategori")</li>
                    <li>@Html.ActionLink("Satışlar", "Index", "Satislar")</li>
                    <li>@Html.ActionLink("Yardım", "Index", "Yardim")</li>
                    <li>@Html.ActionLink("Yeni Admin", "Index", "Admin")</li>
                    <li>@Html.ActionLink("Çıkış", "Index", "Cikis")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcStok/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>